### PR TITLE
Additional simplifications on the pybind11 example

### PR DESCRIPTION
**Pull request by ktbarrett**
I broke up the commits and ordered them in a way so that you can take some or all of them within reason.

Some of the changes I added:
* no longer exported targets, created a config.cmake file, or installed headers
* merged the sources into the pybind11 example file and remove the RPATH stuff
* replace CTest with tox testing since this is supposed to mainly be a python package with cmake being the build system

### CODE REVIEW

**Comment by ktbarrett** [comment]
@henryiii pinging for review.

**Comment by henryiii** [comment]
Sorry, I missed this. Thanks for the ping! Should we duplicate the files after commit 2 and make that an "advanced" example?

**Comment by ktbarrett** [comment]
@henryiii If the advanced example is intended to install the CMake package files into the Python package prefix, then it needs additional work. Without the usage of `cmake_install_dir`, the relative linkage in the CMake package files won't be correct. I have a more advanced example [here](https://github.com/ktbarrett/hello) where I actually worked out the kinks in a similar example.

**Comment by henryiii** [comment]
Thanks! I think it looks fine. I'd like a more involved example too at some point, but hopefully this can get in and then a new one can be added later.

**Pull request merged**
